version: "3"

services:
  # api:
  #   container_name: ${PROJECT_NAME}_api
  #   build:
  #     context: .
  #     dockerfile: ./Deployment/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 8123:8123

  database:
    image: postgres:16
    container_name: ${PROJECT_NAME}_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./Deployment/postgres/.data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ${PROJECT_NAME}_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./Deployment/redis/.data/db:/root/redis
      - ./Deployment/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}

  minio:
    image: minio/minio:latest
    container_name: ${PROJECT_NAME}_minio
    restart: unless-stopped
    ports:
      - "9000:9000"     # S3 API
      - "9001:9001"     # Console
    volumes:
      - ./Deployment/minio/data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

networks:
  docker-network:
    driver: bridge